# Generated by Django 5.2.3 on 2025-06-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='precio',
        ),
    ]
